### ISSUE TITLE
Fetching an invalid anime id throws NameError

### ISSUE THREAD

**Issue by junpet** [JohnDoee/malparser#1]
Reproduce:
```python
from malparser import MAL
mal = MAL()
a = mal.get_anime(2)
a.fetch()
```
---

Result is:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    a.fetch()
  File "\venv\lib\site-packages\malparser\base.py", line 31, in fetch
    return self.mal._fetch(self)
  File "\venv\lib\site-packages\malparser\mal.py", line 23, in _fetch
    time.sleep(i)
NameError: name 'time' is not defined
```
---

Tested on these systems:
Microsoft Windows [Version 10.0.18362.418]
Python 3.8.0

Debian 10 (buster)
Python 3.7.30

---

Probably missing `time` import.

**Comment by JohnDoee** [comment]
Thanks for reporting it, it should be fixed now and a 404 check is added.

The time.sleep is because MAL has some rate limit stuff.
